SmartHome/Controllers/CommandController.cs
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using SmartHome.App_Start;
using SmartHome.Models;
using SmartHome.Models.DataContracts;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Web;
//using System.Web.Http;
using System.Web.Mvc;
using uPLibrary.Networking.M2Mqtt;

namespace SmartHome.Controllers
{
    public class CommandController : Controller
    {
        
        private static UserConfiguration _config = (UserConfiguration)ConfigurationManager.GetSection("UserConfiguration");

        private RootUnit _root;

        private static ConcurrentDictionary<string, string> _commands = new ConcurrentDictionary<string, string>();

        private static MqttClient _mqtt;

        private static object _sync = new object();

        private static ILog _logger = LogManager.GetLogger("CommandController");

        public CommandController()
        {
            var user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<SmartHomeUserManager>().FindByName(System.Web.HttpContext.Current.User.Identity.Name);

            if (user != null && user.Profiles.Any())
            {
                _root = user.Profiles.Where(p => p.Name == user.DefaultProfileName).FirstOrDefault();
                _root.UpdateParents();
            }            

            if (_mqtt == null)
            {
                lock(_sync)
                {
                    if (_mqtt == null)
                    {
                        _mqtt = new MqttClient(ConfigurationManager.AppSettings["mqtt:host"], Convert.ToInt32(ConfigurationManager.AppSettings["mqtt:port"]), false,null,null,MqttSslProtocols.None);
                        _mqtt.ConnectionClosed += MqttReconnect;
                        MqttReconnect(null, null);
                        //_mqtt.Connect("my_unique_identifier", ConfigurationManager.AppSettings["mqtt:user"], ConfigurationManager.AppSettings["mqtt:password"]);
                    }
                }
            }
            
        }

        private void MqttReconnect(object sender, EventArgs e)
        {
            _mqtt.Connect("my_unique_identifier_" + DateTime.Now.Ticks.ToString(), ConfigurationManager.AppSettings["mqtt:user"], ConfigurationManager.AppSettings["mqtt:password"]);
            _mqtt.Subscribe(new string[] { "sensor" }, new byte[] { 0 });
            _mqtt.MqttMsgPublishReceived += (s, args) =>
            {
                var topic = args.Topic;
                var msg = Encoding.UTF8.GetString(args.Message);

                var dto = JsonConvert.DeserializeObject<SensorTO>(msg);

                SetSensorValue(dto.SensorId, dto.SensorValue);
            };
        }

        /// <summary>
        /// Послать команду
        /// </summary>
        /// <param name="command">Имя команды</param>
        /// <param name="target">ClientId объекта, содержащего команду</param>
        [HttpPost]
        public void SendCommand(string command, string target)
        {
            var unit = _root.FindUnit(target);
            if (unit == null) return;

            _commands.AddOrUpdate(target, command, (k, v) => command);

            if (!_mqtt.IsConnected)
            {
                MqttReconnect(null, null);
            }

            //var cmd = String.Format("{{\"command\":\"{0}\", \"target\":\"{1}\"}}", command, target);
            //_mqtt.Publish("command/" + target.Replace("_", "/"), Encoding.ASCII.GetBytes(cmd));

            var cmd = JsonConvert.SerializeObject(new { Command = command, Target = unit.Id });

            //var user = User.Identity.GetUserName();
            var manager = HttpContext.GetOwinContext().GetUserManager<SmartHomeUserManager>();

            SmartHomeUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<SmartHomeUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            var topic = String.Format("{0}/{1}/{2}", user.UserName, user.DefaultProfileName, unit.ClientId.Replace("_", "/"));

            _mqtt.Publish(topic, Encoding.UTF8.GetBytes(cmd));

        }

        [HttpPost]
        public string RecieveCommand(string target)
        {
            string result = null;

            _commands.TryRemove(target, out result);

            return result;
        }

        //[AllowAnonymous]
        [HttpPost]
        public void SetSensorValue(string sensorId, string val)
        {
            _logger.DebugFormat("Start setting sensor {0} value to {1}", sensorId, val);

            SensorBase sensor = null;

            if (_root == null)  // прилетело значение от датчика, поэтому user не определен. Пока считается, что у датчиков id уникальный, поэтому будем искать во всей куче
            {   
                if (_config != null && _config.Users.Any())
                {
                    sensor = _config.Users.SelectMany(u => u.Profiles).Select(r => r.FindSensor(sensorId)).Where(s => s != null).FirstOrDefault();
                }
            }
            else
                sensor = _root.FindSensor(sensorId);

            if (sensor == null)
            {
                _logger.DebugFormat("Sensor {0} not found", sensorId);
                return;
            }

            sensor.Value = val;
            sensor.MeasureTime = DateTime.UtcNow.AddHours(3);

            if (_mqtt.IsConnected)
            {
                //var msg = JsonConvert.SerializeObject(sensor);
                var msg = JsonConvert.SerializeObject(new  { clientid = sensor.ClientId, display = sensor.DisplayName, value = sensor.Value, time = sensor.MeasureTime.Value.ToString("dd.MM HH:mm", new System.Globalization.CultureInfo("ru-RU")) });
                _mqtt.Publish("sensorvalue", Encoding.UTF8.GetBytes(msg));
            }

            sensor.History.Enqueue(new SensorHistoryEntry() { Value = val, MeasureTime = sensor.MeasureTime.Value });

            _logger.DebugFormat("Setting sensor {0} value to {1} successfully finished", sensorId, val);
        }

        public class SensorTO
        {
            [JsonProperty(PropertyName = "sensorId")]
            public string SensorId { get; set; }

            [JsonProperty(PropertyName = "val")]
            public string SensorValue { get; set; }
        }
    }
}

SmartHome/Controllers/HomeController.cs
using log4net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SmartHome.Models;
using SmartHome.Models.DataContracts;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Serialization;

namespace SmartHome.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        //private IRootObject _root;
        private static ILog _logger = LogManager.GetLogger("HomeController");

        private  RootUnit _root;

        //public HomeController(RootUnit root)
        public HomeController()
        {

            var user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<SmartHomeUserManager>().FindByName(System.Web.HttpContext.Current.User.Identity.Name);

            if (user != null && user.Profiles.Any())
            {
                _root = user.Profiles.Where(p => p.Name == user.DefaultProfileName).FirstOrDefault();
                _root.UpdateParents();
            }

            //_root = root;

            //if (_root != null) return;

            //_root = (RootUnit)(ConfigurationManager.GetSection("RootUnit"));
            //_root.UpdateParents();

        }


        public ActionResult MainView()
        {
            return View(_root);
        }

        //public ActionResult Refresh(string id)
        //{
        //    var m = _root.FindCompositeObject(id);

        //    return PartialView("CompositeObject", m);
        //}

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Refresh(string id)
        {
            _logger.DebugFormat("Trying to refresh unit {0}", id);

            var unit = _root.FindUnit(id);

            return PartialView("Sensors", unit.Sensors);

        }
        [HttpGet]
        public ActionResult History(string id)
        {
            _logger.DebugFormat("Trying to get history from sensor {0}", id);

            var sensor = _root.FindSensor(id);

            var result = String.Empty;

            if (sensor != null)
            {
                foreach (var h in sensor.History)
                {
                    result += $"&nbsp;{h.Value}&nbsp;{h.MeasureTime.ToString("dd-MM-yyyy HH:mm")}";
                }
            }

            return Content(result);

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }



        #region tmp

        //private void CreateRootUnit()
        //{
        //    _root = new RootUnit()
        //    {
        //        Id = "root",
        //        Name = "fazenda",
        //        DisplayName = "Фазенда",
        //        Sensors = new List<SensorBase>()
        //        {
        //            new TemperatureSensor() { Id = "airtemp", Name = "temperature", DisplayName = "температура воздуха", HardId = "TM0001" },
        //            new PressureSensor() { Id = "pressure", Name = "pressure", DisplayName = "атмосферное давление", HardId = "PR0001" },
        //        },
        //        Units = new List<CompositeObject>()
        //        {
        //            new House() {
        //                Id = "house",
        //                Name = "house",
        //                DisplayName = "дом",
        //                Sensors = new List<SensorBase>() {
        //                    new TemperatureSensor() { Id = "firstfloor", Name = "firstfloor", DisplayName = "температура на 1 этаже", HardId = "TM0002" },
        //                    new TemperatureSensor() { Id = "secondfloor", Name = "secondfloor", DisplayName = "температура на 2 этаже", HardId = "TM0003" },
        //                },
        //            },
        //            new Greenhouse()
        //            {
        //                Id = "parnik1",
        //                Name = "parnik1",
        //                DisplayName = "теплица 1",
        //                Sensors = new List<SensorBase>()
        //                {
        //                    new TemperatureSensor() { Id = "temperature", Name = "temperature", DisplayName = "температура воздуха", HardId = "TM0004" }
        //                },
        //                Units = new List<CompositeObject>()
        //                {
        //                    new Barrel()
        //                    {
        //                        Id = "barrel1",
        //                        Name = "barrel1",
        //                        DisplayName = "бочка 1",
        //                        Commands = new List<Command>()
        //                        {
        //                            new Command() { Id = "open", Name = "open", DisplayName = "открыть" },
        //                            new Command() { Id = "close", Name = "close", DisplayName = "закрыть" }
        //                        },
        //                        Sensors = new List<SensorBase>()
        //                        {
        //                            new LevelSensor() { Id = "level", Name = "level", DisplayName = "уровень", HardId = "LV0001" }
        //                        }
        //                    },

        //                    new Barrel()
        //                    {
        //                        Id = "barrel2",
        //                        Name = "barrel2",
        //                        DisplayName = "бочка 2",
        //                        Commands = new List<Command>()
        //                        {
        //                            new Command() { Id = "open", Name = "open", DisplayName = "открыть" },
        //                            new Command() { Id = "close", Name = "close", DisplayName = "закрыть" }
        //                        },
        //                        Sensors = new List<SensorBase>()
        //                        {
        //                            new LevelSensor() { Id = "level", Name = "level", DisplayName = "уровень", HardId = "LV0002" }
        //                        }
        //                    }

        //                }
        //            }
        //        }

        //    };

        //    XmlSerializer xs = new XmlSerializer(_root.GetType());

        //    StringWriter sw = new StringWriter();

        //    xs.Serialize(sw, _root);

        //    var s = sw.ToString();

        //    var sr = new StringReader(s);

        //    var f = (RootUnit)xs.Deserialize(sr);

        //    var ss = "ok";

        //}

        #endregion
    }
}

SmartHome/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SmartHome/Views/Home/CompositeObject.cshtml
@using SmartHome.Models.DataContracts;
@model CompositeObject
@{
// ViewBag.Title = "Home Page";
}

    <div id="@Model.Name">

        @if (Model.Sensors != null && Model.Sensors.Any())
        {

            <div id='sensors_@Model.ClientId'>
                <div id='sensorsU_@Model.ClientId'>
                    @*<h4>@Model.DisplayName - показания датчиков</h4>*@
                    @Html.Partial("Sensors", Model.Sensors)
                </div>
            </div>
        }

        @if (Model.Commands != null && Model.Commands.Any())
        {
            <div>
                @foreach (var cmd in Model.Commands)
                {
                    <button type="button" name="@Model.ClientId" id="@cmd.Id" class="btn btn-primary">@cmd.DisplayName</button>
                }
            </div>
            <div class="divider">
                <hr />
            </div>

        }


    @if (Model.Units != null && Model.Units.Any())
    {
        <div class="tabbable tabs-top">
            <ul class="nav nav-tabs">
                @foreach (var cobj in Model.Units)
                {
                    var cl = (cobj.ClientId == Model.Units.FirstOrDefault().ClientId) ? "active" : "";
                    <li class="@cl">
                        <a name="@Model.Name" data-toggle="tab" href="#@cobj.ClientId">@cobj.DisplayName</a>
                    </li>
                }
            </ul>

            <div class="tab-content">
                @foreach (var cobj in Model.Units)
                {
                    var cl = (cobj.ClientId == Model.Units.FirstOrDefault().ClientId) ? "tab-pane fade in active" : "tab-pane fade in";
                    <div id="@cobj.ClientId" class="@cl">
                        @Html.Partial("CompositeObject", cobj)
                    </div>
                }

            </div>
        </div>
    }

</div>






SmartHome/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SmartHome/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SmartHome/Views/Home/MainView.cshtml
@using SmartHome.Models.DataContracts;
@model RootUnit
@{
    ViewBag.Title = Model.DisplayName;
}
<div class="row">


    <div class="panel-group" id="accordion">
        <div class="panel panel-primary">
            <div class="panel-heading row">
                <div class="col-md-11 col-xs-11 col-sm-11"><h4>@Model.DisplayName </h4></div>
                @*<div class="col-md-1 col-xs-1 col-sm-1 text-right"><span class="glyphicon glyphicon-log-out" style="padding-top: 10px; cursor:pointer" onclick="logoff()"></span></div>*@
            </div>
            
        </div>

        @{
            foreach (var s in Model.Units)
            {
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a name="@s.Name" data-toggle="collapse" data-parent="#accordion" href="#@s.ClientId">@s.DisplayName</a>                                                                                        
                        </h4>
                        
                    </div>
                    <div id="@s.ClientId" class="panel-collapse collapse">
                        <div class="panel-body">
                            @Html.Partial("CompositeObject", s)
                        </div>
                    </div>
                </div>

            }
        }

    </div>

</div>

@section scripts {
<script type="text/javascript">

        // Create a client instance
        //client = new Paho.MQTT.Client("host", port, "client_id");
        //client = new Paho.MQTT.Client("m10.cloudmqtt.com", 36425, "web_1234567"/* + parseInt(Math.random() * 100, 10) */);
        client = new Paho.MQTT.Client("m10.cloudmqtt.com", 36425, "web1_" + @DateTime.Now.Ticks);//parseInt(Math.random() * 100, 10) );
        //Example client = new Paho.MQTT.Client("m11.cloudmqtt.com", 32903, "web_" + parseInt(Math.random() * 100, 10));

        reconnect();

        // called when the client connects
        function onConnect() {
            // Once a connection has been made, make a subscription and send a message.
            //debugger;

            $("#msg").text("Connected to MQTT server");
            //client.subscribe("sensor/root/#");
            client.subscribe("sensorvalue");
        }

        function doFail(e) {
            //console.log(e);
            //debugger;
            $("#msg").text("Shit happens - " + e.errorMessage);
        }

        // called when the client loses its connection
        function onConnectionLost(responseObject) {
            //debugger;
            if (responseObject.errorCode !== 0) {
                //console.log("onConnectionLost:" + responseObject.errorMessage);
                $("#msg").text("Connection lost");
            }

            reconnect();
        }

        function reconnect() {

            // set callback handlers
            client.onConnectionLost = onConnectionLost;
            client.onMessageArrived = onMessageArrived;
            var options = {
                cleanSession: false,
                keepAliveInterval: 6000,
                useSSL: true,
                userName: "quefkobd",
                password: "524rVRkbylHl",
                onSuccess: onConnect,
                onFailure: doFail
            }

            // connect the client
            client.connect(options);
        }

        // called when a message arrives
        function onMessageArrived(message) {
            //debugger;
            var dest = message.destinationName;
            var ctrl = dest.replace(/\//g, "_")

            var msg = JSON.parse(message.payloadString);

            //$("#" + msg.ClientId).text(msg.Value);
            $("#" + msg.clientid).replaceWith("<tr id='" + msg.clientid + "'><td>"+ msg.display + "</td><td>" + msg.value + "</td><td>" + msg.time + "</td></tr>");

            @*// здесь надо бы засинхронизировать состояние с сервером
            $.ajax({
                type: 'POST',
                url: '@Url.Action("SetSensorValue", "Command")',
                //url: '/api/Command/' + this.id + "/" + this.name,
                //url: '/api/Command/' + this.id,
                //dataType: "json",
                cache: false,
                contentType: "application/json",
                data: "{\"sensorId\":\"" + ctrl + "\", \"val\":\"" + message.payloadString + "\" }",

                success: function (data) {

                },

                error: function (data) {
                    debugger;
                    alert(data);
                }
            });*@


        }
        //
        //
        //

        var current = null;
        $(function () {
            $(".btn").click(function () {
                //debugger;
                //alert("event=" + "@Model.Id" + " , id=" + this.id + " unit=" + this.name);

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("SendCommand", "Command")',
                    //url: '/api/Command/' + this.id + "/" + this.name,
                    //url: '/api/Command/' + this.id,
                    //dataType: "json",
                    cache: false,
                    contentType: "application/json",
                    data: "{\"command\":\"" + this.id + "\", \"target\":\"" + this.name + "\" }",

                    success: function (data) {

                    },

                    error: function (data) {
                        debugger;
                        alert(data);
                    }
                });

            });

            $("a").click(function () { current = this.name; });

        @*$("#refresh").click(function () {
            //debugger;
            if (current != null) {
                //alert("refreshing " + current);

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Refresh")/' + current,
                    cache: false,
                    beforeSend: function () {
                        //$("#mbbusy").show();
                    },
                    complete: function () {
                        //$("#mbbusy").hide();
                    },

                    success: function (data) {
                        //debugger;
                        //alert(data);
                        // заменяем содержимое присланным частичным представлением
                        $('#'+current).replaceWith(data);
                        //alert($(".mbselect").length);
                    },
                    error: function (err) {
                        //debugger;
                    }
                });

            }
        });*@

        $("#history").on('show.bs.modal', function () {
                alert('The modal is about to be shown. @Url.Action("History")');

            $.ajax({
                type: 'GET',
                url: '@Url.Action("History")',
                cache: false,
                beforeSend: function () {
                    //$("#mbbusy").show();
                    alert('Before sending request to @Url.Action("History")');
                },
                complete: function () {
                    //$("#mbbusy").hide();
                },

                success: function (data) {
                    //debugger;
                    alert(data);
                    // заменяем содержимое присланным частичным представлением
                    $('.modal-body').replaceWith(data);
                    //alert($(".mbselect").length);
                },
                error: function (err) {
                    alert(err);
                    //debugger;
                }
            });

        });
    });

        function refreshObject(clientid) {

            //alert(clientid);

            $.ajax({
                type: 'GET',
                url: '@Url.Action("Refresh")/' + clientid,
                cache: false,
                beforeSend: function () {
                    //$("#mbbusy").show();
                },
                complete: function () {
                    //$("#mbbusy").hide();
                },

                success: function (data) {
                    //debugger;
                    //alert(data);
                    // заменяем содержимое присланным частичным представлением
                    $('#sensorsU_' + clientid).replaceWith(data);
                    //alert($(".mbselect").length);
                },
                error: function (err) {
                    //debugger;
                }
            });

        }

        function logoff()
        {
            //debugger;
            $.ajax({
                type: 'POST',
                url: '@Url.Action("LogOff", "Account")',
                cache: false,
                beforeSend: function () {
                    //$("#mbbusy").show();
                },
                complete: function () {
                    //$("#mbbusy").hide();
                },

                success: function (data) {
                    //debugger;
                },
                error: function (err) {
                    //debugger;
                }
            });

        }

        function showHistory(clientId) {
            //$("#history").modal();

            var url = '@Url.Action("History", "Home")/' + clientId;
            alert(url);

            //alert(clientId);

            $.ajax({
                type: 'GET',
                url: url,
                cache: false,
                beforeSend: function () {
                    //$("#mbbusy").show();
                    alert('History Request is about to be sent');
                },
                complete: function () {
                    //$("#mbbusy").hide();
                },

                success: function (data) {
                    debugger;
                    alert(data);
                    // заменяем содержимое присланным частичным представлением
                    $('.modal-body').replaceWith(data);
                    //alert($(".mbselect").length);
                },
                error: function (jqXHR, textStatus, err) {
                    debugger;
                    alert(err);
                    
                }
            });
        }

</script>
}

SmartHome/Views/Home/Sensors.cshtml

@using SmartHome.Models.DataContracts;
@model List<SensorBase>
@{
    // ViewBag.Title = "Home Page";
    //ViewData["modelId"] = Model[0].Parent.ClientId;
}


    <table class="table table-striped">
        <thead>
            <tr>
                <th>Параметр</th>
                <th>Значение</th>
                <th>Время</th>
                <th>&nbsp;</th>
                @*<th><div class="text-right"><a href="#" class="btn btn-xs btn-info" onclick="refreshObject('@Model[0].Parent.ClientId')"><span class="glyphicon glyphicon-refresh"></span></a></div></th>*@
            </tr>
        </thead>
        <tbody>

            @foreach (var d in Model)
            {
                <tr id="@d.ClientId">
                    <td>@d.DisplayName</td>
                    <td>@d.Value</td>
                    <td>
                        <nobr>
                            @if (d.MeasureTime.HasValue)
                            {
                                @d.MeasureTime.Value.ToString("dd.MM HH:mm", new System.Globalization.CultureInfo("ru-RU"));
                            }
                            else
                            {
                                var history = d.History.FirstOrDefault();
                                if (history != null)
                                {
                                    @history.MeasureTime.ToString("dd.MM HH:mm", new System.Globalization.CultureInfo("ru-RU"));
                                }
                            }
                        </nobr>
                    </td>
                    <td>&nbsp;</td>
                </tr>
            }
        </tbody>
    </table>